names:
- single_arm_iiwa
problems:
    single_arm_iiwa:
        robot: iiwa
        constraint: xyzrpy
        frame: iiwa/iiwa_0_link
        root_frame: map
        custom_planning: false
        prm: 
            filename: /home/kuhnerd/tmp/pd_prm_iiwa_grasping.prm
            save: false
            size: 3000
            visibility_distance: 0.3
        approaching_required: false
        objects:
            names:
            - bottle
            - cup
            objects:
                bottle:
                    model: ${find prm_planner_launch}/models/iiwa_pouring/water_bottle.stl
                    frame_name: bottle
                cup:
                    model: ${find prm_planner_launch}/models/iiwa_pouring/cup.stl
                    frame_name: cup
