general:
    execute_motion: true
    use_shortcuts: true
    verbose: true
    visualize: true
    planner_type: 1                            #0: PRMVisibilityOnly, 1: PRMControl, 2: RRT
    problem_definition: iiwa_pouring
    setup: 0                                                #INTERFACE_SIMULATION = 0, INTERFACE_HARDWARE = 1, INTERFACE_PERFECT_SIMULATION = 2
planning:
    max_planning_time: 60
execution:
    use_hardware_interface_for_execution: true
octomap:
    resolution: 0.025
    prob_hit: 0.7
    prob_miss: 0.4
    clamping_threshold_min: 0.12
    clamping_threshold_max: 0.97
topics:
    camera_rgb: /vrep/rgb/image
    camera_rgb_info: /vrep/rgb/camera_info
    camera_depth: /vrep/depth/image_filtered
    camera_depth_info: /vrep/depth/camera_info
    camera_prefix: "camera"
constraint:
    type: xyzrpy
