joint_limits:
    global_rot1_joint:
        has_velocity_limits: false
        has_acceleration_limits: false
    global_lin_joint:
        has_velocity_limits: false
        has_acceleration_limits: false
    global_rot2_joint:
        has_velocity_limits: false
        has_acceleration_limits: false
    lbr_1_joint:
        has_velocity_limits: true
        max_velocity: 0.1963
        has_acceleration_limits: false
        max_acceleration: 0
    lbr_2_joint:
        has_velocity_limits: true
        max_velocity: 0.1963
        has_acceleration_limits: false
        max_acceleration: 0
    lbr_3_joint:
        has_velocity_limits: true
        max_velocity: 0.1963
        has_acceleration_limits: false
        max_acceleration: 0
    lbr_4_joint:
        has_velocity_limits: true
        max_velocity: 0.1963
        has_acceleration_limits: false
        max_acceleration: 0
    lbr_5_joint:
        has_velocity_limits: true
        max_velocity: 0.1963
        has_acceleration_limits: false
        max_acceleration: 0
    lbr_6_joint:
        has_velocity_limits: true
        max_velocity: 0.1963
        has_acceleration_limits: false
        max_acceleration: 0
    lbr_7_joint:
        has_velocity_limits: true
        max_velocity: 0.1963
        has_acceleration_limits: false
        max_acceleration: 0