names:
- single_arm_omnirob
- tray_dual_arm_omnirob_iiwa
- tray_dual_arm_10d_omnirob_iiwa
- pouring_iiwa
problems:
    single_arm_omnirob:
        robot: omnirob_lbr_sdh2
        constraint: xyzrpy
        frame: omnirob_lbr/base_link
        root_frame: map
        prm: 
            filename: /home/kuhnerd/tmp/pd_prm_single_arm.prm
            save: false
            size: 2000
            visibility_distance: 0.3
        approaching_required: false
    tray_dual_arm_omnirob_iiwa:
        robot: omnirob_iiwa
        constraint: vertical
        frame: omnirob/base_link
        root_frame: map
        prm: 
            filename: /home/kuhnerd/tmp/pd_prm_tray_dual_arm_omnirob_iiwa.prm
            save: false
            size: 2000
            visibility_distance: 0.3
        approaching_required: true
    tray_dual_arm_10d_omnirob_iiwa:
        robot: full_omnirob_iiwa
        constraint: vertical
        frame: iiwa_sdh2/base_link
        root_frame: map
        prm: 
            filename: /home/kuhnerd/tmp/pd_prm_tray_dual_arm_10d_omnirob_iiwa.prm
            save: false
            size: 4000
            visibility_distance: 0.3
        approaching_required: true
    pouring_iiwa:
        robot: iiwa_shd2
        constraint: vertical
        frame: iiwa_sdh2/base_link
        root_frame: map
        prm: 
            filename: /home/kuhnerd/tmp/pd_prm_pouring_iiwa.prm
            save: false
            size: 100
            visibility_distance: 0.1
        approaching_required: true
