names:
- omnirob_lbr_sdh2
- iiwa_sdh2
- omnirob_iiwa
- full_omnirob_iiwa
robots:
  omnirob_lbr_sdh2:
    arm_names:
    - omnirob_lbr_sdh2
    arms:
      omnirob_lbr_sdh2:
        start_link: lbr_0_link
        end_link: sdh2_grasp_link
        description: /omnirob_lbr/robot_description
        tf_prefix: omnirob_lbr
        hand:
          name: sdh2
          joint_state_topic: sdh2/joint_states
  iiwa_sdh2:
    arm_names:
    - iiwa_sdh2
    arms:
      iiwa_sdh2:
        start_link: iiwa_0_link
        end_link: sdh2_grasp_link
        description: /iiwa/iiwa_description
        tf_prefix: iiwa
        hand:
          name: shd2
          joint_state_topic: sdh2/joint_states
  iiwa_sdh2_pouring:
    arm_names:
    - iiwa_sdh2
    arms:
      iiwa_sdh2:
        start_link: iiwa_0_link
        end_link: sdh2_grasp_link
        tool_frame: true #needs to be defined in problem definition class
        description: /iiwa/iiwa_description
        tf_prefix: iiwa
        hand:
          name: shd2
          joint_state_topic: sdh2/joint_states
        prm: 
          file: /home/kuhnerd/tmp/robot_arm_iiwa_sdh2_pouring.prm
          save: false
          size: 2000
          visibility_distance: 0.3
          approaching_planning_frame: iiwa/base_link
          approaching_constraint: horizontal
  omnirob_iiwa:
    arm_names:
    - omnirob_lbr
    - iiwa_sdh2
    arms:
      omnirob_lbr:
        start_link: lbr_0_link
        end_link: lbr_7_link
        description: /omnirob_lbr/robot_description
        tf_prefix: omnirob_lbr
        hand:
          name: sdh2
          joint_state_topic: sdh2/joint_states
        prm: 
          file: /home/kuhnerd/tmp/robot_arm_prm_omnirob_lbr_sdh2.prm
          save: false
          size: 2000
          visibility_distance: 0.3
          approaching_planning_frame: omnirob/base_link
          approaching_constraint: xyzrpy
      iiwa_sdh2:
        start_link: iiwa_0_link
        end_link: sdh2_grasp_link
        description: /iiwa/robot_description
        tf_prefix: iiwa
      hand:
        name: shd2
        joint_state_topic: sdh2/joint_states
      prm: 
        filename: /home/kuhnerd/tmp/robot_arm_prm_iiwa_sdh2.prm
        save: false
        size: 2000
        visibility_distance: 0.3
        approaching_planning_frame: iiwa/base_link
        approaching_constraint: xyzrpy
  full_omnirob_iiwa:
    arm_names:
    - omnirob_full
    - iiwa_sdh2
    arms:
      omnirob_full:
        start_link: global_base_link_1
        end_link: sdh2_grasp_link
        description: /omnirob_full/robot_description
        tf_prefix: omnirob_full
        hand:
          name: sdh_omnirob
          joint_state_topic: omnirob_full/joint_states
        prm:
          filename: /home/kuhnerd/tmp/robot_arm_prm_omnirob_10d_sdh2.prm
          save: false
          size: 8000
          visibility_distance: 0.3
          approaching_planning_frame: omnirob_full/global_base_link_1
      iiwa_sdh2:
        start_link: iiwa_0_link
        end_link: sdh2_grasp_link
        description: /iiwa_sdh2/robot_description
        tf_prefix: iiwa_sdh2
        hand:
          name: sdh_iiwa
          joint_state_topic: iiwa_sdh2/joint_states
        prm:
          filename: /home/kuhnerd/tmp/robot_arm_prm_iiwa_sdh2.prm
          save: false
          size: 2000
          visibility_distance: 0.3
          approaching_planning_frame: iiwa_sdh2/base_link  
#defines sample limits for joints without joint limits
#provide arm names here
joint_limits:
  omnirob_full:
    joints:
    - global_rot1_joint
    - global_lin_joint
    - global_rot2_joint
    global_rot1_joint:
      sample_limit_min: -pi
      sample_limit_max: pi  
    global_lin_joint:
      sample_limit_min: -2.5
      sample_limit_max: 2.5    
    global_rot2_joint:
      sample_limit_min: -pi
      sample_limit_max: pi          
controller_configs:
  #++++++++++++++++++++++++++++++++++++++++++++++
  #++++++++ OMNIROB +++++++++++++++++++++++++++++
  #++++++++++++++++++++++++++++++++++++++++++++++
  omnirob_lbr:
    ########### 
    vrep:
      ###########
      executing_controller:
        name: VelocityController7DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 3.0
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
          
      ###########
      simulating_controller:
        name: VelocityController7DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2
    
    ###########
    robot:
      ###########
      executing_controller:
        name: VelocityController7DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 3.0
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
          
      ###########
      simulating_controller:
        name: VelocityController7DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2
          
  #++++++++++++++++++++++++++++++++++++++++++++++
  #++++++++ OMNIROB SDH2 ++++++++++++++++++++++++
  #++++++++++++++++++++++++++++++++++++++++++++++
  omnirob_lbr_sdh2:
    ########### 
    vrep:
      ###########
      executing_controller:
        name: VelocityController7DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 3.0
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
          
      ###########
      simulating_controller:
        name: VelocityController7DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2
    
    ###########
    robot:
      ###########
      executing_controller:
        name: VelocityController7DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 3.0
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
          
      ###########
      simulating_controller:
        name: VelocityController7DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2
  #++++++++++++++++++++++++++++++++++++++++++++++
  #++++++++ FULL OMNIROB ++++++++++++++++++++++++
  #++++++++++++++++++++++++++++++++++++++++++++++
  omnirob_full:
    ###########
    vrep:
      ###########
      executing_controller:
        name: VelocityController7Plus3DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: true
          vel_0: 0.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.1
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
      
      ###########
      simulating_controller:
        name: VelocityController7Plus3DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2
          
    ###########
    robot:
      ###########
      executing_controller:
        name: VelocityController7Plus3DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: true
          vel_0: 3.0
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
        
      ###########
      simulating_controller:
        name: VelocityController7Plus3DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2
          
  #++++++++++++++++++++++++++++++++++++++++++++++
  #++++++++ iiwa ++++++++++++++++++++++++++++++++
  #++++++++++++++++++++++++++++++++++++++++++++++
  iiwa_sdh2:
    ###########
    vrep:
      ###########
      executing_controller:
        name: VelocityController7DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 3.0
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
          
      ###########
      simulating_controller:
        name: VelocityController7DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2
          
    ###########
    robot:
      ###########
      executing_controller:
        name: VelocityController7DOF
        frequency: 250
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 3.0
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 1.0
        max_task_vel:
          linear: 0.05
          angular: 0.2
        joint_range_weight:
          default: 0.3
          std: 0.3
          
      ###########
      simulating_controller:
        name: VelocityController7DOF
        frequency: 100
        max_velocity: 0.7
        k:
        - 10
        - 10
        - 10
        - 3
        - 3
        - 3
        lambda: 1.7
        least_square_lambda_max: 0.04
        least_square_epsilon: 0.04
        debug: false
        goal_dist_pos: 0.015
        goal_dist_ang: 0.02
        collision_avoidance:
          use: false
          vel_0: 1.5
          distance_1: 0.2
          distance_2: 0.5
          max_vel: 0.7
          ratio_do_collision_checks: 0.3
        max_task_vel:
          linear: 0.05
          angular: 0.2